### PR TITLE
formatInline rewrite

### LINKED ISSUE #59: FormatInline "small" does not get removed
I have written a command to format a text as `<small>`. This works as expected.
But removing the tag does not work because `<small>` is declared as a different nodetype than for instance `<b>`.

The command can be seen here: https://github.com/Waxolunist/bootstrap3-wysihtml5-bower/blob/v0.3.0-wip/src/commands/small.js

I have written a test: https://github.com/Waxolunist/bootstrap3-wysihtml5-bower/blob/v0.3.0-wip/test/bootstrap_editor_commands_test.js

The two last assertions do not work.

### LINKED ISSUE #83: foreColorStyle bug - color disapears and selection gets confused
Hi there,
i found a strange behaviour, setting inline styles.
Please look at this example and follow the instructions.
http://jsfiddle.net/4maweav6/1/

To explain it here too:
When you select a multiline text and give it a color, the color will be set (even if there are b- or i-elements). When you insert a b or i tag, select the whole text again, the div wrapped the text where the new b/i element is set, gets black and an empty span gets prepended to the body with the old color style.

Has anyone an idea how to fix this?

thanks and regards
tammo

### LINKED ISSUE #86: Multiple colors possible on same selection
Here is a way how you can have two colors on the same selection:

Go to http://edicy.github.io/wysihtml5/examples/advanced.html
Type "Test" and select it. Set the color to red, make it bold, set the color to blue.

What i expected: it turns the color class attribute from red to blue
What happens: a span gets inserted inside the bold tag and the menu shows that there are both colors set to the selection.

### LINKED ISSUE #87: Cannot turn off formatting
Scenario:
1. Select a formatting (for example, bold)
2. Type some text
3. Turn off the previously selected formatting
4. Press Enter, type some more text
Expected behaviour: The newly entered text is not formatted
Actual behaviour: The newly entered text is still being formatted as bold.
Issue present in Chrome 37

### LINKED ISSUE #100: formatInline does not work
Im using wysihtml5x 0.4.16 and formatInline command does not work. 

I have a Toolbar-Button with command "formatInline" and value "strong".
When i already have a strong tag inside the text an click on the button the strong tag gets removed, that works. But when i have selected normal text and click on the button the text is not bold, but all formatting in the box has gone!

### LINKED ISSUE #120: Toggle bold 3 times doesn't work
Repro (in Chrome 38.0.2125.104 on a mac)

1. http://wysihtml.com/
2. Highlight some text, e.g. 'typing'
3. Click the bold icon in the top left three times

Expected:
The word 'typing' becomes bold, reverts to normal, then becomes bold again.

Actual:
The word 'typing' becomes bold, reverts to normal, but isn't bold again. (NB. the bold icon does end up emphasised)

screen shot 2014-12-18 at 17 49 40

### LINKED ISSUE #143: Formatting is not switched off after whitespace
1. http://wysihtml.com/
2. Click the bold icon
3. Type some text
4. Click the bold icon again to switch it off
5. Press "space" to add a whitespace
6. Start typing again 

Expected:
Bold is switched off

Actual:
The new text after the whitespace is also bold

bold

### LINKED ISSUE #166: Removing formatting from element after moving cursor then coming back - broken
Hello,
It's pretty basic - moving a cursor after applying a formatting, then going back to remove the formatting does not work and throws errors.

Here's a simple .gif to show: 
wysihtml

It does seem to be a pretty major issue since it breaks one of the most basic functionalities.

### PR DESCRIPTION
**Pull request by pulges**
Complete rewrite of formatInline logic with tag / style / class / attribute / support

## Logic

**Non-collapsed selection:**

* [x] Format is applied on selection if the current format state is not active
* [x] Format is also applied on selection if the current format state only partially active (extends format)
* [x] Format is removed if the content of selection is fully in active state
* [x] Selection is preserved always for easy toggle

**Collapsed selection:**

* [x] Format is applied if caret position is not in active state
* [x] If caret is on word boundary (textNode context) or outside of word format is applied/removed around caret depending on state
* [x] If caret is in word (textNode context), the format is applied/removed on the word depending on current state
* [x] Caret selection is preserved event when applying format on word

**Both:**

* [x] Similar classes (classRegExp provided) and similar styles (same styleProperty name) are managed and not wrapped inside each other
* [x] Also handles attributes addition/removal on element
* [x] Consequent textnodes are joined after modifications
* [x] Consequent similar format tags are joined after modifications
* [x] Empty format nodes are removed after modifications
* [x] B and STRONG, I and EM should be interchangeable
* [x] removing styles or classes without defining tag should keep the tag unless span

Related issues:
* [x] Fixes #166 - Removing formatting from element after moving cursor then coming back - broken
* [x] Fixes #143 - Formatting is not switched off after whitespace
* [x] Fixes #120 - Toggle bold 3 times doesn't work
* [x] Fixes #100 - formatInline does not work
* [x] Fixes #87 - Cannot turn off formatting
* [x] Fixes #86 - Multiple colors possible on same selection 
* [x] Fixes #83 - ForeColorStyle bug - color disapears and selection gets confused
* [x] Fixes #59 - FormatInline "small" does not get removed

**Other:**
* [x] Write Tests Covering formatInline spec
* [x] Write tests Covering former issues
* [x] Update commands for new syntax

### CODE REVIEW

File: src/commands/formatInline.js [hunk 1]
```diff
@@ -1,150 +1,628 @@
...
+  // If nodeName is specified inline node with the same (or alias) nodeName is expected to prove similar regardless of attributes
+  function isSimilarNode(node, options) {
+    var o;
+    if (options.nodeName) {
+      var query = queryAliasMap[options.nodeName.toLowerCase()] || options.nodeName.toLowerCase();
+      return wysihtml5.dom.domNode(node).test({ query: query });
+    } else {
+      o = wysihtml5.lang.object(options).clone();
+      o.query = INLINE_ELEMENTS; // make sure only inline elements with styles and classes are counted
+      return wysihtml5.dom.domNode(node).test(options);
```
Comment (Aintaer) [inline src/commands/formatInline.js]: Seems like `options` should be `o` here? Otherwise the query options are not modified.
